### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by till** [krakjoe/apcu-bc#15]
Kind of lost between apcu and apcu-bc and php7. 

Wouldn't mind a readme? ;)

**Comment by frickenate** [comment]
No kidding... we all just got left in the dust.

After a bit of experimentation, the results: you need to install _both_ packages. `apt-get install php-apcu` (possibly php7-apcu, php70-apcu, php7.0-apcu, etc) _and_ `pecl install channel://peor cl.php.net/apcu_bc-1.0.3` to get the compatibility layer (can't simplify to `pecl install apcu_bc` as it's a beta release rather than stable).

**Comment by krakjoe** [comment]
APC documentation covers the BC layer.
APCu documentation is now present in the manual: http://php.net/apcu
